- name: Soda
  price: 1.50
  event_price: 2.50
  currency: SODA
  category: drink
- name: Fritz
  price: 2.00
  event_price: 3.00
  currency: FRITZ
  category: drink
- name: Club Mate
  price: 2.00
  event_price: 3.00
  currency: CM
  category: drink
- name: Water
  price: 0.50
  event_price: 0.75
  currency: WATER
  category: drink
- name: Tea
  price: 0.50
  event_price: 0.75
  currency: TEA
  category: drink
- name: Jupiler
  price: 1.50
  event_price: 2.50
  currency: JUPILER
  category: alcohol
- name: Duvel
  price: 2.50
  event_price: 3.50
  currency: DUVEL
  category: alcohol
- name: Chimay
  price: 4.00
  event_price: 6.00
  currency: CHIMAY
  category: alcohol
- name: Snack
  price: 0.60
  event_price: 0.90
  currency: SNACK
  category: food
- name: Ice Cream
  price: 1.00
  event_price: 1.50
  currency: ICE_CREAM
  category: food
- name: Pizza
  # Also listed as 3.50
  price: 2.00
  event_price: 3.50
  currency: PIZZA
  payback:
    account: Liabilities:Bar:Members:Bart
    amount: 1.63
  category: food
- name: Wristband
  price: 1.00
  event_price: 1.50
  currency: WRISTBAND
  payback:
    account: Liabilities:Bar:Members:Marquis
    amount: 0.50
  category: swag
- name: T-Shirt
  price: 20.00
  event_price: 30.00
  currency: TSHIRT
  category: swag
- name: Hoodie
  price: 35.00
  event_price: 53.00
  currency: HOODIE
  category: swag
#- name: Club Mate Red
#  price: 2.00
#  event_price: 3.00
#  currency: CMRED
#  category: drink
#- name: Club Mate Kraftstoff
#  currency: CMKRAFT
#  price: 2.00
#  event_price: 3.00
#  category: drink
#- name: Club Mate Cola
#  price: 2.00
#  event_price: 3.00
#  currency: CMCOLA
#  category: drink
#- NAME: FANTA
#  PRICE: 2.00
#  EVENT_PRICE: 3.00
#  CURRENCY: FANTA
#  CATEGORY: DRINK
#- NAME: SPRITE
#  PRICE: 2.00
#  EVENT_PRICE: 3.00
#  CURRENCY: SPRITE
#  CATEGORY: DRINK
#- NAME: SCHWEPPES
#  PRICE: 2.00
#  EVENT_PRICE: 3.00
#  CURRENCY: SCWEPPES
#  CATEGORY: DRINK
#- name: Chips
#  price: 0.60
#  event_price: 0.90
#  currency: CHIP
#  category: food
#- name: "whole #!"
#  price: 20.00
#  event_price: 30.00
#  currency: WHOLENUM
#  category: misc
#- name: Snickers
#  price: 0.50
#  event_price: 0.75
#  currency: SNICKERS
#  category: food
#- name: Twix
#  price: 0.50
#  event_price: 0.75
#  currency: TWIX
#  category: food
#- name: Ice Tea
#  price: 2.50
#  event_price: 3.50
#  category: drink
#  currency: ICETEA
#- name: Cola
#  price: 2.50
#  event_price: 3.50
#  currency: COKE
#  category: drink
#- name: Cola Light
#  price: 2.50
#  event_price: 3.50
#  currency: COKE_LIGHT
#  category: drink
#- name: Cola Zero
#  price: 1.50
#  event_price: 2.50
#  currency: COKE_ZERO
#  category: drink
#- name: Mars
#  price: 0.50
#  event_price: 0.75
#  currency: MARS
#  category: food
#- name: Cha-Cha
#  price: 0.50
#  event_price: 0.75
#  currency: CHACHA
#  category: food
#- name: Cider
#  price: 1.00
#  event_price: 1.50
#  currency: CIDER
#  category: alcohol
#- name: "M&M"
#  price: 0.50
#  event_price: 0.75
#  currency: MNM
#  category: food
#- name: Joylent
#  price: 7.00
#  event_price: 10.00
#  currency: JOYLENT
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 5.00
#- name: Curry
#  price: 5.00
#  event_price: 7.50
#  currency: CURRY
#  category: food
#- name: Kriek
#  price: 2.00
#  event_price: 3.00
#  currency: KRIEK
#  category: alcohol
#- name: Croque
#  price: 1.50
#  event_price: 2.25
#  currency: CROQUE
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 1.00
#  category: food
#- name: Jenever
#  price: 2.00
#  event_price: 3.00
#  category: alcohol
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 1.00
#  currency: JNVR
#- name: KitKat
#  price: 0.50
#  event_price: 0.75
#  category: food
#  currency: KITKAT
#- name: Leffe
#  price: 2.00
#  event_price: 3.00
#  category: alcohol
#  currency: LEFFE
#- name: Orval
#  price: 3.00
#  event_price: 4.50
#  category: alcohol
#  currency: ORVL
