# ----- current visible list ------
# Cold drinks:
- name: Soda
  price: 1.50
  event_price: 2.50
  currency: SODA
  category: drink
  visible: True
- name: Cecemel
  price: 0.70
  event_price: 1.00
  currency: CHOCO_MILK
  category: drink
  visible: False
- name: Fritz / Club Mate Cola
  price: 2.50
  event_price: 3.50
  currency: GERMAN
  category: drink
  visible: True
- name: Club Mate
  price: 3.00
  event_price: 4.00
  currency: CM
  category: drink
  visible: True

# Warm drinks:
- name: Tea
  price: 0.50
  event_price: 0.75
  currency: TEA
  category: drink
  visible: False    

# Alcohol:
- name: Beer
  price: 1.50
  event_price: 2.50
  currency: BEER
  category: alcohol
  visible: True
- name: Fancy Beer
  price: 2.50
  event_price: 3.50
  currency: DUVEL
  category: alcohol
  visible: True
- name: Cider
  price: 2.00
  event_price: 3.00
  currency: CIDER
  category: alcohol
  visible: True
- name: Cocktail
  price: 4.00
  event_price: 6.00
  currency: COCKTAIL
  category: alcohol
  visible: True

# Snacks etc:
- name: Snack Bar
  price: 0.60
  event_price: 1.00
  currency: SNACK
  category: food
  visible: True
- name: Chips
  price: 1.00
  event_price: 1.50
  currency: CHIP
  category: food
  visible: True
  
# Swag:
- name: Wristband
  price: 1.00
  event_price: 1.50
  currency: WRISTBAND
  payback:
    account: Liabilities:Bar:Members:Marquis
    amount: 0.50
  visible: True
  category: swag
- name: T-Shirt
  price: 15.00
  event_price: 15.00
  currency: TSHIRT
  category: swag
  visible: True
- name: Hoodie
  price: 25.00
  event_price: 25.00
  currency: HOODIE
  category: swag
  visible: True
- name: Passport
  price: 2.50
  event_price: 3.60
  currency: PASSPORT
  payback:
    account: Liabilities:Bar:Members:Bart
    amount: 1.20
  category: swag
  visible: True
- name: Postcard
  price: 2.50
  event_price: 3.50
  currency: POSTCARD
  payback:
    account: Liabilities:Bar:Members:NewlineJar
    amount: 1.00

# ----- end current visible list -----
# ----- legacy/removed items: -----
# catchall

- name: Fanta
  price: 1.50
  event_price: 2.50
  currency: FANTA
  category: drink
  visible: False
- name: Ice Tea
  price: 1.50
  event_price: 2.50
  category: drink
  currency: ICETEA
  visible: False
- name: Ice Tea Zero
  price: 1.50
  event_price: 2.50
  category: drink
  currency: ICETEA_ZERO
  visible: False
- name: Cola
  price: 1.50
  event_price: 2.50
  currency: COKE
  category: drink
  visible: False
- name: Cola Zero
  price: 1.50
  event_price: 2.50
  currency: COKE_ZERO
  category: drink
  visible: False
- name: Schweppes
  price: 1.50
  event_price: 2.50
  currency: SCHWEPPES
  category: drink
  visible: False
- name: Agrumes
  price: 1.50
  event_price: 2.50
  currency: AGRUMES
  category: drink
  visible: False
- name: Expired drink
  price: 0.60
  event_price: 0.60
  currency: EXPIRED_DRINK
  category: drink
  visible: False

# weird german stuff
# catchall

- name: Fritz
  price: 2.50
  event_price: 3.50
  currency: FRITZ
  category: drink
  visible: False
- name: Fritz Zero
  price: 2.50
  event_price: 3.50
  currency: FRITZ_ZERO
  category: drink
  visible: False
- name: Club Mate Red
  price: 2.00
  event_price: 3.00
  currency: CMRED
  category: drink
  visible: False
- name: Club Mate Cola
  price: 2.50
  event_price: 3.50
  category: drink
  currency: CMCOLA
  visible: False
- name : Club Mate Winter
  price: 2.00
  event_price: 3.00
  category: drink
  currency: WINTER_MATE
  visible: False
- name: Flora Power
  price: 2.00
  event_price: 3.00
  category: drink
  currency: FLORA
  visible: False
- name : "Vitamalz"
  price: 2.00
  event_price: 3.00
  category: drink
  currency: VITAMALZ
  visible: False

# plain drinks
#- name: Water (glass)
#  price: 0.50
#  event_price: 0.50
#  currency: WATER_GLASS
#  category: drink
- name: Water (bottle)
  price: 0.75
  event_price: 1.00
  currency: WATER
  category: drink
  visible: True

- name: Kombucha
  price: 3.00
  event_price: 3.50
  currency: KOMBUCHA
  category: drink
  visible: True

# alcoholics
- name: Jupiler
  price: 1.50
  event_price: 2.50
  currency: JUPILER
  category: alcohol
  visible: False
- name: Chimay
  price: 2.50
  event_price: 4.00
  currency: CHIMAY
  category: alcohol
  visible: False
- name: Wine
  price: 1.50
  event_price: 3.00
  currency: WINE
  category: alcohol
  visible: True
- name: Kriek
  price: 1.50
  event_price: 2.50
  currency: KRIEK
  category: alcohol
  visible: False
- name: Hoegaarden
  price: 1.50
  event_price: 2.50
  currency: HG
  category: alcohol
  visible: False
- name: Mystery Beer
  price: 2.50
  event_price: 3.50
  currency: MYSTERY
  category: alcohol
  visible: False
- name: SpacePils
  price: 1.33
  event_price: 3.14
  currency: CARA
  category: alcohol
  visible: True

# snacks
# catchall

- name: Croque
  price: 1.5
  event_price: 2.00
  currency: CROQUE
  category: food
  visible: False
- name: Loempia
  price: 2.00
  event_price: 3.00
  currency: LOEMPIA
  category: food
  visible: False
- name: Food
  price: 3.50
  event_price: 5.00
  currency: FOOD
  category: food
  visible: False
- name: FOOD 2.5
  price: 2.50
  event_price: 3.75
  currency: FOOD2.5
  category: food
  visible: False
- name: Snickers
  price: 0.60
  event_price: 0.90
  currency: SNICKERS
  category: food
  visible: False
- name: Twix
  price: 0.60
  event_price: 0.90
  currency: TWIX
  category: food
  visible: False
- name: Mars
  price: 0.60
  event_price: 0.90
  currency: MARS
  category: food
  visible: False
- name: "M&M"
  price: 0.60
  event_price: 0.90
  currency: MNM
  category: food
  visible: False
- name: KitKat
  price: 0.60
  event_price: 0.90
  category: food
  currency: KITKAT
  visible: False
- name: Leo
  price: 0.60
  event_price: 0.90
  currency: LEO
  category: food
  visible: False
- name: King Mints
  price: 0.60
  event_price: 0.90
  category: food
  currency: KING
  visible: False
- name: "1 Chupa Chups"
  price: 0.20
  event_price: 0.30
  currency: CHUPACHUPS
  category: food
  visible: False
- name: "Rolo"
  price: 0.60
  event_price: 0.90
  category: food
  currency: ROLO
  visible: False
- name: Popcorn
  price: 0.50
  event_price: 0.50
  currency: POPCORN
  category: food
  visible: False
- name: Bounty
  price: 0.60
  event_price: 0.90
  currency: BOUNTY
  category: food
  visible: False
- name: Lion
  price: 0.60
  event_price: 0.90
  currency: LION
  category: food
  visible: False
- name: Pick Up!
  price: 0.70
  event_price: 1.05
  currency: PICKUP
  category: food
  visible: False
- name: ROM
  price: 1.00
  event_price: 1.50
  currency: ROM
  category: food
  payback:
    account: Liabilities:Bar:Members:Thequux
    amount: 0.50
  visible: False
- name: Food Cup
  price: 1.20
  event_price: 2.00
  currency: FOOD_CUP
  category: food
  visible: False
- name: Nākd
  price: 1.20
  event_price: 2.00
  currency: NAKD
  category: food
  visible: False

# frozen goods
- name: Ice Cream
  price: 1.00
  event_price: 1.50
  currency: ICE_CREAM
  category: food
  payback:
    account: Liabilities:Bar:Members:Yvan
    amount: 0.63
  visible: False
- name: Pizza
  # Also listed as 3.50
  price: 2.50
  event_price: 4.00
  currency: PIZZA
  category: food
  payback:
    account: Liabilities:Bar:Members:Yvan
    amount: 1.50
  visible: False

#- name: Facemask
#  price: 4.00
#  event_price: 4.00
#  currency: FACEMASK
#  category: swag
# unused products below

#- name: Soda
#  price: 1.50
#  event_price: 2.50
#  currency: SODA
#  category: drink
#- name: Club Mate Kraftstoff
#  currency: CMKRAFT
#  price: 2.00
#  event_price: 3.00
#  category: drink
- name: SPRITE
  price: 2.00
  event_price: 3.00
  currency: SPRITE
  category: DRINK
  visible: False
#- name: "whole #!"
#  price: 20.00
#  event_price: 30.00
#  currency: WHOLENUM
#  category: misc
#- name: Cola Light
#  price: 2.50
#  event_price: 3.50
#  currency: COKE_LIGHT
#  category: drink
- name: Cha-Cha
  price: 0.50
  event_price: 0.75
  currency: CHACHA
  category: food
  visible: False
#- name: Cider
#  price: 1.00
#  event_price: 1.50
#  currency: CIDER
#  category: alcohol
#- name: Joylent
#  price: 7.00
#  event_price: 10.00
#  currency: JOYLENT
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 5.00
#- name: Curry
#  price: 5.00
#  event_price: 7.50
#  currency: CURRY
#  category: food
#- name: Croque
#  price: 1.50
#  event_price: 2.25
#  currency: CROQUE
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 1.00
#  category: food
#- name: Jenever
#  price: 2.00
#  event_price: 3.00
#  category: alcohol
#  payback:
#    account: Liabilities:Bar:Members:Bloemist
#    amount: 1.00
#  currency: JNVR
- name: Leffe
  price: 2.00
  event_price: 3.00
  category: alcohol
  currency: LEFFE
  visible: False
- name: Orval
  price: 3.00
  event_price: 4.50
  category: alcohol
  currency: ORVL
  visible: False
